# permissions for end users to view secretcopiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretcopier-viewer-role
rules:
- apiGroups:
  - apps.muthukadan.net
  resources:
  - secretcopiers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.muthukadan.net
  resources:
  - secretcopiers/status
  verbs:
  - get
