# permissions for end users to edit secretcopiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretcopier-editor-role
rules:
- apiGroups:
  - apps.muthukadan.net
  resources:
  - secretcopiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.muthukadan.net
  resources:
  - secretcopiers/status
  verbs:
  - get
